### ISSUE TITLE
[Feature Request] Add Beam Search as decoding strategy

### ISSUE THREAD

**Issue by LTluttmann** [ai4co/rl4co#109]
Hey there, 

first, big thanks for making this awesome library open source. I wish I would have discovered it earlier, would have probably saved me several hours of work ;) 

One thing I was missing though is the beam search decoding strategy. Do you already plan on adding it in the future? Otherwise I would be happy to help with that 

## Motivation
Beam search can lead to significant improvements of the solution quality of the trained model (e.g. Kool et al., 2018)

## Solution

This would probably require a base decoding strategy class, where the different strategies (greedy, sampling, beam search) would define a *step* function, called in every iteration of the autoregressive decoder. Also, something like a *post_decoder_hook*, where the backtracking of the beam search (and the concatenation of the actions in the other sampling strategies) takes place, would be required. 

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by fedebotu** [comment]
Hi @LTluttmann !
I definitely agree; beam search would be great to have. We didn't have a defined plan in mind for it so far due to the many things to do including features that will be added in the near future in RL4CO. If you can help us to implement beam search, it would be awesome! 🚀
Feel free to contact us any time~
